package com.ec.mutualistapichincha.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Funcionario implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String paso;
   private java.lang.String agenciaSolicitud;
   private java.lang.String tipoAgencia;
   private java.lang.Integer codigoOficialCuenta;
   private java.lang.Integer codigoProducto;
   private java.lang.String nombreProducto;
   private java.lang.String grupoTipoCredito;
   private java.lang.String tipoGarantia;
   private java.lang.String tipoCliente;
   private java.lang.String tipoPersona;
   private java.lang.Integer residencia;
   private java.lang.Double montoSolicitado;
   private java.lang.String requiereVerificacionDatos;
   private java.lang.String estadoEmpleado;
   private java.lang.String funcionEmpleado;
   private java.lang.String grupoEmpleado;
   private java.lang.String buscarPorAgenciaSolicitud;
   private java.lang.String cargoRRHH;
   private java.lang.String nombreVariableGestorSolicitud;
   private java.lang.String descripcionUsuarioPrincipal;
   private java.lang.String funcionEmpleadoAlterno;
   private java.lang.String grupoEmpleadoAlterno;
   private java.lang.String descripcionUsuarioAlterno;

   public Funcionario()
   {
   }

   public java.lang.String getPaso()
   {
      return this.paso;
   }

   public void setPaso(java.lang.String paso)
   {
      this.paso = paso;
   }

   public java.lang.String getAgenciaSolicitud()
   {
      return this.agenciaSolicitud;
   }

   public void setAgenciaSolicitud(java.lang.String agenciaSolicitud)
   {
      this.agenciaSolicitud = agenciaSolicitud;
   }

   public java.lang.String getTipoAgencia()
   {
      return this.tipoAgencia;
   }

   public void setTipoAgencia(java.lang.String tipoAgencia)
   {
      this.tipoAgencia = tipoAgencia;
   }

   public java.lang.Integer getCodigoOficialCuenta()
   {
      return this.codigoOficialCuenta;
   }

   public void setCodigoOficialCuenta(java.lang.Integer codigoOficialCuenta)
   {
      this.codigoOficialCuenta = codigoOficialCuenta;
   }

   public java.lang.Integer getCodigoProducto()
   {
      return this.codigoProducto;
   }

   public void setCodigoProducto(java.lang.Integer codigoProducto)
   {
      this.codigoProducto = codigoProducto;
   }

   public java.lang.String getNombreProducto()
   {
      return this.nombreProducto;
   }

   public void setNombreProducto(java.lang.String nombreProducto)
   {
      this.nombreProducto = nombreProducto;
   }

   public java.lang.String getGrupoTipoCredito()
   {
      return this.grupoTipoCredito;
   }

   public void setGrupoTipoCredito(java.lang.String grupoTipoCredito)
   {
      this.grupoTipoCredito = grupoTipoCredito;
   }

   public java.lang.String getTipoGarantia()
   {
      return this.tipoGarantia;
   }

   public void setTipoGarantia(java.lang.String tipoGarantia)
   {
      this.tipoGarantia = tipoGarantia;
   }

   public java.lang.String getTipoCliente()
   {
      return this.tipoCliente;
   }

   public void setTipoCliente(java.lang.String tipoCliente)
   {
      this.tipoCliente = tipoCliente;
   }

   public java.lang.String getTipoPersona()
   {
      return this.tipoPersona;
   }

   public void setTipoPersona(java.lang.String tipoPersona)
   {
      this.tipoPersona = tipoPersona;
   }

   public java.lang.Integer getResidencia()
   {
      return this.residencia;
   }

   public void setResidencia(java.lang.Integer residencia)
   {
      this.residencia = residencia;
   }

   public java.lang.Double getMontoSolicitado()
   {
      return this.montoSolicitado;
   }

   public void setMontoSolicitado(java.lang.Double montoSolicitado)
   {
      this.montoSolicitado = montoSolicitado;
   }

   public java.lang.String getRequiereVerificacionDatos()
   {
      return this.requiereVerificacionDatos;
   }

   public void setRequiereVerificacionDatos(
         java.lang.String requiereVerificacionDatos)
   {
      this.requiereVerificacionDatos = requiereVerificacionDatos;
   }

   public java.lang.String getEstadoEmpleado()
   {
      return this.estadoEmpleado;
   }

   public void setEstadoEmpleado(java.lang.String estadoEmpleado)
   {
      this.estadoEmpleado = estadoEmpleado;
   }

   public java.lang.String getFuncionEmpleado()
   {
      return this.funcionEmpleado;
   }

   public void setFuncionEmpleado(java.lang.String funcionEmpleado)
   {
      this.funcionEmpleado = funcionEmpleado;
   }

   public java.lang.String getGrupoEmpleado()
   {
      return this.grupoEmpleado;
   }

   public void setGrupoEmpleado(java.lang.String grupoEmpleado)
   {
      this.grupoEmpleado = grupoEmpleado;
   }

   public java.lang.String getBuscarPorAgenciaSolicitud()
   {
      return this.buscarPorAgenciaSolicitud;
   }

   public void setBuscarPorAgenciaSolicitud(
         java.lang.String buscarPorAgenciaSolicitud)
   {
      this.buscarPorAgenciaSolicitud = buscarPorAgenciaSolicitud;
   }

   public java.lang.String getCargoRRHH()
   {
      return this.cargoRRHH;
   }

   public void setCargoRRHH(java.lang.String cargoRRHH)
   {
      this.cargoRRHH = cargoRRHH;
   }

   public java.lang.String getNombreVariableGestorSolicitud()
   {
      return this.nombreVariableGestorSolicitud;
   }

   public void setNombreVariableGestorSolicitud(
         java.lang.String nombreVariableGestorSolicitud)
   {
      this.nombreVariableGestorSolicitud = nombreVariableGestorSolicitud;
   }

   public java.lang.String getDescripcionUsuarioPrincipal()
   {
      return this.descripcionUsuarioPrincipal;
   }

   public void setDescripcionUsuarioPrincipal(
         java.lang.String descripcionUsuarioPrincipal)
   {
      this.descripcionUsuarioPrincipal = descripcionUsuarioPrincipal;
   }

   public java.lang.String getFuncionEmpleadoAlterno()
   {
      return this.funcionEmpleadoAlterno;
   }

   public void setFuncionEmpleadoAlterno(
         java.lang.String funcionEmpleadoAlterno)
   {
      this.funcionEmpleadoAlterno = funcionEmpleadoAlterno;
   }

   public java.lang.String getGrupoEmpleadoAlterno()
   {
      return this.grupoEmpleadoAlterno;
   }

   public void setGrupoEmpleadoAlterno(java.lang.String grupoEmpleadoAlterno)
   {
      this.grupoEmpleadoAlterno = grupoEmpleadoAlterno;
   }

   public java.lang.String getDescripcionUsuarioAlterno()
   {
      return this.descripcionUsuarioAlterno;
   }

   public void setDescripcionUsuarioAlterno(
         java.lang.String descripcionUsuarioAlterno)
   {
      this.descripcionUsuarioAlterno = descripcionUsuarioAlterno;
   }

   public Funcionario(java.lang.String paso, java.lang.String agenciaSolicitud,
         java.lang.String tipoAgencia, java.lang.Integer codigoOficialCuenta,
         java.lang.Integer codigoProducto, java.lang.String nombreProducto,
         java.lang.String grupoTipoCredito, java.lang.String tipoGarantia,
         java.lang.String tipoCliente, java.lang.String tipoPersona,
         java.lang.Integer residencia, java.lang.Double montoSolicitado,
         java.lang.String requiereVerificacionDatos,
         java.lang.String estadoEmpleado, java.lang.String funcionEmpleado,
         java.lang.String grupoEmpleado,
         java.lang.String buscarPorAgenciaSolicitud, java.lang.String cargoRRHH,
         java.lang.String nombreVariableGestorSolicitud,
         java.lang.String descripcionUsuarioPrincipal,
         java.lang.String funcionEmpleadoAlterno,
         java.lang.String grupoEmpleadoAlterno,
         java.lang.String descripcionUsuarioAlterno)
   {
      this.paso = paso;
      this.agenciaSolicitud = agenciaSolicitud;
      this.tipoAgencia = tipoAgencia;
      this.codigoOficialCuenta = codigoOficialCuenta;
      this.codigoProducto = codigoProducto;
      this.nombreProducto = nombreProducto;
      this.grupoTipoCredito = grupoTipoCredito;
      this.tipoGarantia = tipoGarantia;
      this.tipoCliente = tipoCliente;
      this.tipoPersona = tipoPersona;
      this.residencia = residencia;
      this.montoSolicitado = montoSolicitado;
      this.requiereVerificacionDatos = requiereVerificacionDatos;
      this.estadoEmpleado = estadoEmpleado;
      this.funcionEmpleado = funcionEmpleado;
      this.grupoEmpleado = grupoEmpleado;
      this.buscarPorAgenciaSolicitud = buscarPorAgenciaSolicitud;
      this.cargoRRHH = cargoRRHH;
      this.nombreVariableGestorSolicitud = nombreVariableGestorSolicitud;
      this.descripcionUsuarioPrincipal = descripcionUsuarioPrincipal;
      this.funcionEmpleadoAlterno = funcionEmpleadoAlterno;
      this.grupoEmpleadoAlterno = grupoEmpleadoAlterno;
      this.descripcionUsuarioAlterno = descripcionUsuarioAlterno;
   }

}