package com.ec.mutualistapichincha.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InterFecha implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.Date fechaActual;
   private java.util.Date fechaUltimoInforme;
   private java.util.Date fechaUltimaActualizacion;
   private java.lang.String requiereVT;

   public InterFecha()
   {
   }

   public java.util.Date getFechaActual()
   {
      return this.fechaActual;
   }

   public void setFechaActual(java.util.Date fechaActual)
   {
      this.fechaActual = fechaActual;
   }

   public java.util.Date getFechaUltimoInforme()
   {
      return this.fechaUltimoInforme;
   }

   public void setFechaUltimoInforme(java.util.Date fechaUltimoInforme)
   {
      this.fechaUltimoInforme = fechaUltimoInforme;
   }

   public java.util.Date getFechaUltimaActualizacion()
   {
      return this.fechaUltimaActualizacion;
   }

   public void setFechaUltimaActualizacion(
         java.util.Date fechaUltimaActualizacion)
   {
      this.fechaUltimaActualizacion = fechaUltimaActualizacion;
   }

   public java.lang.String getRequiereVT()
   {
      return this.requiereVT;
   }

   public void setRequiereVT(java.lang.String requiereVT)
   {
      this.requiereVT = requiereVT;
   }

   public InterFecha(java.util.Date fechaActual,
         java.util.Date fechaUltimoInforme,
         java.util.Date fechaUltimaActualizacion, java.lang.String requiereVT)
   {
      this.fechaActual = fechaActual;
      this.fechaUltimoInforme = fechaUltimoInforme;
      this.fechaUltimaActualizacion = fechaUltimaActualizacion;
      this.requiereVT = requiereVT;
   }

}