package com.ec.mutualistapichincha.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Puntos implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal puntosPropuestos;

   private java.lang.String requiereAprobacion;

   public Puntos()
   {
   }

   public java.math.BigDecimal getPuntosPropuestos()
   {
      return this.puntosPropuestos;
   }

   public void setPuntosPropuestos(java.math.BigDecimal puntosPropuestos)
   {
      this.puntosPropuestos = puntosPropuestos;
   }

   public java.lang.String getRequiereAprobacion()
   {
      return this.requiereAprobacion;
   }

   public void setRequiereAprobacion(java.lang.String requiereAprobacion)
   {
      this.requiereAprobacion = requiereAprobacion;
   }

   public Puntos(java.math.BigDecimal puntosPropuestos,
         java.lang.String requiereAprobacion)
   {
      this.puntosPropuestos = puntosPropuestos;
      this.requiereAprobacion = requiereAprobacion;
   }

}