package com.cloudbanco.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PorcentajePTC implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double monto;
   private java.lang.Double ptc;
   private java.lang.String superaPorcentaje;

   public PorcentajePTC()
   {
   }

   public java.lang.Double getMonto()
   {
      return this.monto;
   }

   public void setMonto(java.lang.Double monto)
   {
      this.monto = monto;
   }

   public java.lang.Double getPtc()
   {
      return this.ptc;
   }

   public void setPtc(java.lang.Double ptc)
   {
      this.ptc = ptc;
   }

   public java.lang.String getSuperaPorcentaje()
   {
      return this.superaPorcentaje;
   }

   public void setSuperaPorcentaje(java.lang.String superaPorcentaje)
   {
      this.superaPorcentaje = superaPorcentaje;
   }

   public PorcentajePTC(java.lang.Double monto, java.lang.Double ptc,
         java.lang.String superaPorcentaje)
   {
      this.monto = monto;
      this.ptc = ptc;
      this.superaPorcentaje = superaPorcentaje;
   }

}