package com.cloudbanco.credito.reglas;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Score implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer valor;
   private java.lang.String resultadoScore;
   private java.lang.String resultado;

   public Score()
   {
   }

   public java.lang.Integer getValor()
   {
      return this.valor;
   }

   public void setValor(java.lang.Integer valor)
   {
      this.valor = valor;
   }

   public java.lang.String getResultadoScore()
   {
      return this.resultadoScore;
   }

   public void setResultadoScore(java.lang.String resultadoScore)
   {
      this.resultadoScore = resultadoScore;
   }

   public java.lang.String getResultado()
   {
      return this.resultado;
   }

   public void setResultado(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

   public Score(java.lang.Integer valor, java.lang.String resultadoScore,
         java.lang.String resultado)
   {
      this.valor = valor;
      this.resultadoScore = resultadoScore;
      this.resultado = resultado;
   }

}